<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot1_arm.xacro">
<xacro:include filename="$(find robot_urdf)/urdf/robot1_arm.gazebo"/>
<xacro:include filename="$(find robot_urdf)/urdf/materials.xacro" />   
	
	<!-- static parameters -->
	<xacro:property name="length_wheel" value="0.04" />
	<xacro:property name="radius_wheel" value="0.1" />
	<xacro:property name="link_length" value="0.2"/>
	<xacro:property name="link_radius" value="0.04"/>

	<!-- macro for cylinder inertia -->
	<xacro:macro name="cylinder_inertia" params="mass r l o_rpy"> 
		<inertial>

			<mass value="${mass}" />
			<origin rpy="${o_rpy}" xyz="0 0 0"/>  
	    <inertia ixx="${mass*(3*r*r+l*l)/12}" ixy = "0" ixz = "0" iyy="${mass*(3*r*r+l*l)/12}" iyz = "0" izz="${mass*(r*r)/2}" /> 

	  </inertial>
 	</xacro:macro>

	<!-- macro for cylinder geometry -->
  <xacro:macro name="cylinder_geometry" params="r l">
		<geometry>
       	<cylinder length="${l}" radius="${r}"/>
    </geometry>
	</xacro:macro>

	<!-- link wheel macro -->
	<xacro:macro name="link_wheel" params="name">
        <link name="${name}">
          	<xacro:cylinder_inertia mass="0.2" r="${radius_wheel}" l="${length_wheel}" o_rpy="0 1.5707 1.5707"/>
            <collision name="${name}_collision">
              <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
              <xacro:cylinder_geometry r="${radius_wheel}" l="${length_wheel}"/>
            </collision>
            <visual name="${name}_visual">
              <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
              <xacro:cylinder_geometry r="${radius_wheel}" l="${length_wheel}"/>
            </visual>
        </link>
    </xacro:macro>

	<!-- joint wheel macro -->
    <xacro:macro name="joint_wheel" params="name child parent origin_xyz">
      <joint name="${name}" type="continuous">
        <origin rpy="0 0 0" xyz="${origin_xyz}"/>
        <child link="${child}"/>
        <parent link="${parent}"/>
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <limit effort="10000" velocity="1000"/>
        <joint_properties damping="1.0" friction="1.0"/>
      </joint>
    </xacro:macro>

    <!-- arm link macro -->
		<xacro:macro name="link_arm" params="name">
        <link name="${name}">
          	<xacro:cylinder_inertia mass="0.025" r="${link_radius}" l="${link_length}" o_rpy="0 0 0"/>
            <collision name="${name}_collision">
              <origin xyz="0 0 ${0.5*link_length}" rpy="0 0 0"/> 
              <xacro:cylinder_geometry r="${link_radius}" l="${link_length}"/>
            </collision>
            <visual name="${name}_visual">
              <origin xyz="0 0 ${0.5*link_length}" rpy="0 0 0"/> 
              <xacro:cylinder_geometry r="${link_radius}" l="${link_length}"/>
            </visual>
        </link>
    </xacro:macro>

    <!-- revolute joint arm link macro -->
    <xacro:macro name="joint_link" params="name ax lower upper parent child origin_xyz">
      <joint name="${name}" type="revolute">
	  	<axis xyz="${ax}"/>
	  	<limit effort="1000.0" lower="${lower}" upper="${upper}" velocity="0.2"/>
	  	<origin rpy="0 0 0" xyz="${origin_xyz}"/>
	  	<parent link="${parent}"/>
	  	<child link="${child}"/>
      </joint>
    </xacro:macro>

    <!-- chassis definition -->
    <link name="base_link">

	    <!-- pose and inertial -->
	    <pose>0 0 0.1 0 0 0</pose>
	    
	    <inertial>
	      <mass value="5"/>
	      <origin rpy="0 0 0" xyz="0 0 0.1"/>
	      <inertia ixx="0.0395416666667" ixy="0" ixz="0" iyy="0.106208333333" iyz="0" izz="0.106208333333"/>
	    </inertial>
	    
	    <collision name="collision_chassis">
	      <geometry>
	        <box size="0.5 0.3 0.07"/>
	      </geometry>
	    </collision>
	    
	    <visual>
	      <origin rpy="0 0 0" xyz="0 0 0"/>
	      <geometry>
	        <box size="0.5 0.3 0.07"/>
	      </geometry>
	      <material name="blue"/>
	    </visual>
    
	    <!-- caster front -->
	    <collision name="caster_front_collision">
	      <origin rpy=" 0 0 0" xyz="0.35 0 -0.05"/>
	      <geometry>
	        <sphere radius="0.05"/>
	      </geometry>
	      <surface>
	        <friction>
	          <ode>
	            <mu>0</mu>
	            <mu2>0</mu2>
	            <slip1>1.0</slip1>
	            <slip2>1.0</slip2>
	          </ode>
	        </friction>
	      </surface>
	    </collision>
	    <visual name="caster_front_visual">
	      <origin rpy=" 0 0 0" xyz="0.2 0 -0.05"/>
	      <geometry>
	        <sphere radius="0.05"/>
	      </geometry>
	    </visual>

    </link>

    <!-- hokuyo laser link -->
	  <link name="hokuyo_laser_link">
	        <collision>
	            <origin xyz="0 0 0" rpy="0 0 0"/>
	            <geometry>
	                <cylinder length="0.04" radius="0.045"/>
	            </geometry>
	        </collision>
	        <visual>
	            <origin xyz="0 0 0" rpy="0 0 0"/>
	            <geometry>
	                <mesh filename="package://robot_urdf/meshes/sensors/hokuyo/hokuyo.dae"/>
	            </geometry>
	            <material name="green"/>
	        </visual>
	        <inertial>
	            <mass value="1e-5" />
	            <origin xyz="0 0 0" rpy="0 0 0"/>
	            <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
	        </inertial>
	  </link>

	  <joint name="hokuyo_laser_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0.205 0 0.055" rpy="0 0 0"/>
				<parent link="base_link"/>
        <child link="hokuyo_laser_link"/>
    </joint>

    <!-- Create wheels -->  

    <xacro:link_wheel name="link_right_wheel" />
    <xacro:link_wheel name="link_left_wheel" />
    <xacro:joint_wheel name="joint_right_wheel" child="link_right_wheel" parent="base_link" origin_xyz="-0.05 0.15 0"  />
    <xacro:joint_wheel name="joint_left_wheel" child="link_left_wheel" parent="base_link" origin_xyz="-0.05 -0.15 0"  />

    <!--arm definition -->

	  <link name="arm_base_link">
	  	<inertial>
	  		<mass value="0.1"/>
	  		<origin xyz="0 0 0" rpy="0 0 0" />
	  		<inertia ixx="0.0000416666667" ixy="0" ixz="0" iyy="0.0000416666667" iyz="0" izz="0.0000416666667"/>
	  	</inertial>
	  	<collision>
	  	  <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
	        <box size="0.1 0.1 0.1"/>
	      </geometry>
	  	</collision>
	  	<visual>
	  	  <origin xyz="0 0 0" rpy="0 0 0"/>
	      <geometry>
	        <box size="0.1 0.1 0.1"/>
	      </geometry>
	      <material name="red" />
	  	</visual>
	  </link>

	  <!-- Create Arms, links and joints --> 
 
    <xacro:link_arm name="arm_link_01" />
    <xacro:link_arm name="arm_link_02" />

	  <joint name="arm_base_to_base" type="continuous">
	  	<parent link="base_link"/>
	  	<child link="arm_base_link"/>
	  	<axis xyz="0 0 1"/>
	  	<origin rpy="0 0 0" xyz="0 0 0.085"/>
	  </joint>

    <xacro:joint_link name="joint_link_01" ax="1 0 0" lower="-3.14" upper="3.14" parent="arm_base_link" child="arm_link_01" origin_xyz="0 0 0.05"  />

    <xacro:joint_link name="joint_link_02" ax="1 0 0" lower="-1.8" upper="1.8" parent="arm_link_01" child="arm_link_02" origin_xyz="0 0 ${link_length}"  />

    <!-- Transmission (Motors) for ros_control plugin -->

    <transmission name="arm_joint_01_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="arm_base_to_base">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="motor1">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				<mechanicalInterface>1</mechanicalInterface>
			</actuator>
		</transmission>

		<transmission name="arm_joint_02_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="joint_link_01">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="motor2">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				<mechanicalInterface>1</mechanicalInterface>
			</actuator>
		</transmission>

		<transmission name="arm_joint_03_trans">
			<type>transmission_interface/SimpleTransmission</type>
			<joint name="joint_link_02">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
			</joint>
			<actuator name="motor3">
				<hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
				<mechanicalInterface>1</mechanicalInterface>
			</actuator>
		</transmission>


   
</robot>