joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_base_to_base
    pid: {p: 0.5, i: 0.0, d: 0.05}

joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_link_01
    pid: {p: 0.5, i: 0.0, d: 0.05}

joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_link_02
    pid: {p: 1, i: 0.0, d: 0.05}